version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: todolistbot_postgres
    environment:
      POSTGRES_DB: todolistbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todolistbot_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/todolistbot
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - TELEGRAM_BOT_TOKEN=your_bot_token_here
      - TELEGRAM_BOT_USERNAME=@YourBotUsername
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: